export APP_SECRET_KEY='YOUR-SECRET-KEY'
export SQL_DATABASE_URI='mysql+pymysql://snypit:YOUR-PASSWORD@localhost:3306/snypit'
export VERIFY_EMAIL_SERIALIZER_SECRET='YOUR-EMAIL-SERIALIZER-SECRET-KEY'
export VERIFY_EMAIL_SALT='A-SALT'
export FLASK_APP=run.py
