"""Updated snippet id column name

Revision ID: 183eff716018
Revises: f8f2c91b33ee
Create Date: 2019-03-24 10:41:29.653606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '183eff716018'
down_revision = 'f8f2c91b33ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippet', sa.Column('vzsid', sa.String(length=32), nullable=True))
    op.drop_column('snippet', 'snippet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippet', sa.Column('snippet_id', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('snippet', 'vzsid')
    # ### end Alembic commands ###
