"""Added password reset token table

Revision ID: 62dd2971b2d4
Revises: d9d437264224
Create Date: 2019-03-18 12:17:43.103913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62dd2971b2d4'
down_revision = 'd9d437264224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pwtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pw_reset_token', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pwtoken_user_id'), 'pwtoken', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pwtoken_user_id'), table_name='pwtoken')
    op.drop_table('pwtoken')
    # ### end Alembic commands ###
