"""empty message

Revision ID: 9b3b18ebb47f
Revises: 253f6b756646
Create Date: 2019-03-16 21:03:10.410253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b3b18ebb47f'
down_revision = '253f6b756646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=150), nullable=True))
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', mysql.VARCHAR(length=150), nullable=True))
    op.add_column('user', sa.Column('last_name', mysql.VARCHAR(length=150), nullable=True))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
