"""Added vzin to user table

Revision ID: d9d437264224
Revises: 9b3b18ebb47f
Create Date: 2019-03-17 20:57:00.484817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d437264224'
down_revision = '9b3b18ebb47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('vzin', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'vzin')
    # ### end Alembic commands ###
