"""Added language icon to snippet t table

Revision ID: e0c0cd098c08
Revises: 183eff716018
Create Date: 2019-03-24 13:15:08.381439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c0cd098c08'
down_revision = '183eff716018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippet', sa.Column('language_icon', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snippet', 'language_icon')
    # ### end Alembic commands ###
